### ISSUE TITLE
Game crashed using team battle

### ISSUE THREAD

**Issue by Maselia464** [Flemmli97/MobBattle#30] opened 2023-09-01 17:41 UTC
### Modloader

Forge

### Minecraft version

1.19.4

### Modloader version

4.10

### Mod version

mobbattle-1.19.4-2.4.6-forge.jar

### Description

Hello,

Issue occur when you use the blue stick to do battle with multiple mods

### Steps to reproduce

1. Step one: create two box with two different stick
2 make then fight
3 crash

### Logs

The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.LivingEntity.m_6095_()" because "livingEntity" is null****

**Comment by Maselia464** [comment] 2023-09-01 17:41
Also game keep^crashing after first crash

**Comment by Maselia464** [comment] 2023-09-01 17:50
Update on the issue: when their is too many entity the game crash no matter the spawning method

**Comment by Maselia464** [comment] 2023-09-03 17:17
Update on issue: game crash if 8 mods are involved in a battle:
The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.LivingEntity.m_6095_()" because "livingEntity" is null

Same error

**Comment by Flemmli97** [comment] 2023-09-11 19:59
dupe of #29

**Closed as completed by Flemmli97** 2023-09-11 19:59 UTC
