### ISSUE TITLE
Crash with team fight

### ISSUE THREAD

**Issue by KaratFeng** [Flemmli97/MobBattle#32] opened 2023-09-07 20:14 UTC
### Modloader

Forge

### Minecraft version

1.18.2

### Modloader version

forge 40.2.7

### Mod version

mobbattle-1.18.2-2.4.6-forge.jar

### Description

The game crash when using the blue team wand, or the team command

### Steps to reproduce

1 Add mobs to a team
2 add mobs to another team
3 let them fight
3 game crash

### Logs

[crash-2023-09-07_16.09.09-server.txt](https://github.com/Flemmli97/MobBattle/files/12553068/crash-2023-09-07_16.09.09-server.txt)
[2023-09-07-4.log](https://github.com/Flemmli97/MobBattle/files/12553070/2023-09-07-4.log)

**Comment by jokoast** [comment] 2023-09-09 11:47
Same issue here, after 10 "Team1" summoned Iron Golem

**Comment by Flemmli97** [comment] 2023-09-11 19:59
dupe of #29

**Closed as completed by Flemmli97** 2023-09-11 19:59 UTC
